#!/usr/bin/env python3
"""Convert an image into a 1-bit bitmap header for Dotty's e-paper.

Crops a square, resizes, boosts contrast and dithers to black/white, then writes a
C++ header with an Adafruit_GFX::drawBitmap() compatible array (rows MSB-first,
padded to whole bytes, set bit = black) plus a PNG preview of the result.

Example:
  python3 tools/img2epd.py ~/Downloads/profile.png include/images/sleep_portrait.h \\
      --name kSleepPortrait --size 150 --crop 160 300 1000 --dither atkinson
"""

import argparse
from pathlib import Path

from PIL import Image, ImageEnhance, ImageOps


def atkinson(img):
    """Atkinson dithering: spreads only 3/4 of the error, so it keeps more contrast
    and cleaner whites than Floyd-Steinberg; suits small 1-bit screens."""
    w, h = img.size
    px = [[float(img.getpixel((x, y))) for x in range(w)] for y in range(h)]
    out = Image.new("1", (w, h), 1)
    for y in range(h):
        for x in range(w):
            old = px[y][x]
            new = 255 if old >= 128 else 0
            out.putpixel((x, y), 1 if new else 0)
            err = (old - new) / 8
            for dx, dy in ((1, 0), (2, 0), (-1, 1), (0, 1), (1, 1), (0, 2)):
                if 0 <= x + dx < w and y + dy < h:
                    px[y + dy][x + dx] += err
    return out


def convert(src, size, crop, dither, contrast, brightness):
    img = Image.open(src).convert("L")
    if crop:
        left, top, side = crop
        img = img.crop((left, top, left + side, top + side))
    else:
        img = ImageOps.fit(img, (min(img.size),) * 2)
    img = img.resize((size, size), Image.LANCZOS)
    img = ImageOps.autocontrast(img, cutoff=1)
    img = ImageEnhance.Brightness(img).enhance(brightness)
    img = ImageEnhance.Contrast(img).enhance(contrast)
    if dither == "atkinson":
        return atkinson(img)
    if dither == "floyd":
        return img.convert("1", dither=Image.Dither.FLOYDSTEINBERG)
    return img.point(lambda v: 255 if v >= 128 else 0).convert("1", dither=Image.Dither.NONE)


def to_header(bw, name, source):
    w, h = bw.size
    row_bytes = (w + 7) // 8
    data = []
    for y in range(h):
        for bx in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = bx * 8 + bit
                if x < w and bw.getpixel((x, y)) == 0:  # black pixel -> set bit
                    byte |= 0x80 >> bit
            data.append(byte)
    lines = [", ".join(f"0x{b:02X}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
    body = ",\n    ".join(lines)
    return (
        "#pragma once\n\n"
        "#include <Arduino.h>\n\n"
        f"// Generated by tools/img2epd.py from {source}. Do not edit by hand.\n"
        f"// {w}x{h}, 1 bit per pixel, rows MSB-first, set bit = black.\n"
        f"constexpr int16_t {name}Width = {w};\n"
        f"constexpr int16_t {name}Height = {h};\n"
        f"const uint8_t {name}[] PROGMEM = {{\n    {body}\n}};\n"
    )


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("src")
    p.add_argument("header")
    p.add_argument("--name", required=True, help="C++ identifier for the array")
    p.add_argument("--size", type=int, default=150)
    p.add_argument("--crop", type=int, nargs=3, metavar=("LEFT", "TOP", "SIDE"),
                   help="square crop in source pixels (default: centred square)")
    p.add_argument("--dither", choices=["atkinson", "floyd", "threshold"], default="atkinson")
    p.add_argument("--contrast", type=float, default=1.2)
    p.add_argument("--brightness", type=float, default=1.05)
    p.add_argument("--preview", help="PNG preview path (default: next to the header)")
    args = p.parse_args()

    bw = convert(args.src, args.size, args.crop, args.dither, args.contrast, args.brightness)
    header = Path(args.header)
    header.parent.mkdir(parents=True, exist_ok=True)
    header.write_text(to_header(bw, args.name, Path(args.src).name))
    preview = Path(args.preview) if args.preview else header.with_suffix(".preview.png")
    bw.resize((args.size * 4, args.size * 4), Image.NEAREST).save(preview)
    print(f"wrote {header} and {preview}")


if __name__ == "__main__":
    main()
